define dso_local ptr @fopen_output_safely(ptr noundef %0, ptr noundef %1)
define dso_local i32 @main(i32 noundef %0, ptr noundef %1)
define dso_local void @BZ2_bsInitWrite(ptr noundef %0)
define dso_local void @BZ2_compressBlock(ptr noundef %0, i8 noundef zeroext %1)
define dso_local void @BZ2_blockSort(ptr noundef %0)
define dso_local void @BZ2_bz__AssertH__fail(i32 noundef %0)
define dso_local ptr @BZ2_bzlibVersion()
define dso_local i32 @BZ2_bzCompressInit(ptr noundef %0, i32 noundef %1, i32 noundef %2, i32 noundef %3)
define dso_local i32 @BZ2_bzCompress(ptr noundef %0, i32 noundef %1)
define dso_local i32 @BZ2_bzCompressEnd(ptr noundef %0)
define dso_local i32 @BZ2_bzDecompressInit(ptr noundef %0, i32 noundef %1, i32 noundef %2)
define dso_local i32 @BZ2_indexIntoF(i32 noundef %0, ptr noundef %1)
define dso_local i32 @BZ2_bzDecompress(ptr noundef %0)
define dso_local i32 @BZ2_bzDecompressEnd(ptr noundef %0)
define dso_local ptr @BZ2_bzWriteOpen(ptr noundef %0, ptr noundef %1, i32 noundef %2, i32 noundef %3, i32 noundef %4)
define dso_local void @BZ2_bzWrite(ptr noundef %0, ptr noundef %1, ptr noundef %2, i32 noundef %3)
define dso_local void @BZ2_bzWriteClose(ptr noundef %0, ptr noundef %1, i32 noundef %2, ptr noundef %3, ptr noundef %4)
define dso_local void @BZ2_bzWriteClose64(ptr noundef %0, ptr noundef %1, i32 noundef %2, ptr noundef %3, ptr noundef %4, ptr noundef %5, ptr noundef %6)
define dso_local ptr @BZ2_bzReadOpen(ptr noundef %0, ptr noundef %1, i32 noundef %2, i32 noundef %3, ptr noundef %4, i32 noundef %5)
define dso_local void @BZ2_bzReadClose(ptr noundef %0, ptr noundef %1)
define dso_local i32 @BZ2_bzRead(ptr noundef %0, ptr noundef %1, ptr noundef %2, i32 noundef %3)
define dso_local void @BZ2_bzReadGetUnused(ptr noundef %0, ptr noundef %1, ptr noundef %2, ptr noundef %3)
define dso_local i32 @BZ2_bzBuffToBuffCompress(ptr noundef %0, ptr noundef %1, ptr noundef %2, i32 noundef %3, i32 noundef %4, i32 noundef %5, i32 noundef %6)
define dso_local i32 @BZ2_bzBuffToBuffDecompress(ptr noundef %0, ptr noundef %1, ptr noundef %2, i32 noundef %3, i32 noundef %4, i32 noundef %5)
define dso_local ptr @BZ2_bzopen(ptr noundef %0, ptr noundef %1)
define dso_local ptr @BZ2_bzdopen(i32 noundef %0, ptr noundef %1)
define dso_local i32 @BZ2_bzread(ptr noundef %0, ptr noundef %1, i32 noundef %2)
define dso_local i32 @BZ2_bzwrite(ptr noundef %0, ptr noundef %1, i32 noundef %2)
define dso_local i32 @BZ2_bzflush(ptr noundef %0)
define dso_local void @BZ2_bzclose(ptr noundef %0)
define dso_local ptr @BZ2_bzerror(ptr noundef %0, ptr noundef %1)
define dso_local void @BZ2_hbMakeCodeLengths(ptr noundef %0, ptr noundef %1, i32 noundef %2, i32 noundef %3)
define dso_local void @BZ2_hbAssignCodes(ptr noundef %0, ptr noundef %1, i32 noundef %2, i32 noundef %3, i32 noundef %4)
define dso_local void @BZ2_hbCreateDecodeTables(ptr noundef %0, ptr noundef %1, ptr noundef %2, ptr noundef %3, i32 noundef %4, i32 noundef %5, i32 noundef %6)
define dso_local i32 @BZ2_decompress(ptr noundef %0)
